# commit to be tagged for the new release
commit = "HEAD"

project_name = "bldr"
github_repo = "siderolabs/bldr"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.5.0"
pre_release = false

# [notes]
